train:  C:\Users\Aatif\Desktop\Artikate_Studio\Wood Surface Defects.v1i.yolov8\train\images
val:  C:\Users\Aatif\Desktop\Artikate_Studio\Wood Surface Defects.v1i.yolov8\valid\images
test:  C:\Users\Aatif\Desktop\Artikate_Studio\Wood Surface Defects.v1i.yolov8\test\images

nc: 1
names: ['Defect']

roboflow:
  workspace: project
  project: wood-surface-defects
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/project/wood-surface-defects/dataset/1